version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # database_api:
  #   build:
  #     context: ./database-api/database-api
  #     dockerfile: Dockerfile
  #   container_name: database_api
  #   restart: always
  #   ports:
  #     - '5000:80'
  #     - '5001:443'
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__Database=Host=postgres;Database=postgres;Username=postgres;Password=postgres
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
